# Formulae (command-line tools)
brew "fzf"
brew "fd"
brew "thefuck"
brew "bat"
brew "git-delta"
brew "nvim"
brew "eza"
brew "tlrc"
brew "zoxide"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "spicetify-cli"
brew "ripgrep"
brew "gh"
brew "nvim"

